import Connection.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS-NB
 */
public class biodata_mhs extends javax.swing.JFrame {

    private static void setModel(DefaultTableModel model) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static int getSelectedRow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static Object getValueAt(int baris, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   

    /**
     * Creates new form biodata_mhs
     */
    public biodata_mhs() {
        initComponents();
        Koneksi();
        Tampilan();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLable1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        cbJurusan = new javax.swing.JComboBox<>();
        txtNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cbAngkatan = new javax.swing.JComboBox<>();
        cbFakultas = new javax.swing.JComboBox<>();
        txtAlamat = new javax.swing.JTextField();
        bnSimpan = new javax.swing.JButton();
        bnRefresh = new javax.swing.JButton();
        bnUbah = new javax.swing.JButton();
        bnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bnBatal = new javax.swing.JButton();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Biodata Mahasiswa");

        jLable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLable1.setText("Nim :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nama :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Angkatan :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Jenis Kelamin :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal Lahir :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Alamat :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Fakultas :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Jurusan :");

        cbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Akuntansi", "Teknik Informatika", "Teknik Lingkungan" }));

        cbAngkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013" }));

        cbFakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ekonomi", "TI" }));

        bnSimpan.setText("Simpan");
        bnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSimpanActionPerformed(evt);
            }
        });

        bnRefresh.setText("Refresh");
        bnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnRefreshActionPerformed(evt);
            }
        });

        bnUbah.setText("Ubah Data");
        bnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnUbahActionPerformed(evt);
            }
        });

        bnHapus.setText("Hapus Data");
        bnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnHapusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        bnBatal.setText("Batal");
        bnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnBatalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbLaki);
        rbLaki.setText("Laki Laki");

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbLaki)
                                        .addGap(28, 28, 28)
                                        .addComponent(rbPerempuan))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLable1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(bnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLable1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbLaki)
                        .addComponent(rbPerempuan)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnSimpan)
                    .addComponent(bnRefresh)
                    .addComponent(bnUbah)
                    .addComponent(bnHapus)
                    .addComponent(bnBatal))
                .addGap(74, 74, 74)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSimpanActionPerformed
        // TODO add your handling code here:String nim= txtNim.getText();
        String nim = txtNim.getText();
        String nama = txtNama.getText();
        String jeniskelamin = null;
        if (rbLaki.isSelected()) {
            jeniskelamin = "L";
        }
        else if (rbPerempuan.isSelected()) {
    jeniskelamin = "P";
}
        String tanggal_lahir = txtTanggal.getText();
        String alamat = txtNim.getText();
        String jurusan = (String) cbJurusan.getSelectedItem();
        String fakultas = (String)cbFakultas.getSelectedItem();
        String angkatan = (String)cbAngkatan.getSelectedItem();
        if (txtNim.getText().trim().equals("")) {
} else {
     try {
         java.sql.Statement statement = konekasi.getConnection.creatStatement();
         ResultSet data = Statatement.executeUpdate("SELECT * FROM biodata_mhs WHERE nim ='" + txtNim.getText() + "'");
         if (data.next()) {
         } else {
             String jenis_kelamin = null;
             String tanggal_Lahir = null;
            String sql = "INSERT INTO tabelmahasiswa VALUES('" + nim + "'"
                   + ",'" + nama + "'"
                   + ",'" + jenis_kelamin + "'"
                    + ",'" + tanggal_Lahir + "'"
                    + ",'" + alamat + "'"
                    + ",'" + jurusan + "'"
                   + ",'" + fakultas + "'"
                   + ",'" + angkatan + "')";
            statement.executeUpdate(sql);
            txtNim.setText("");
            txtNama.setText("");
            String jenisKelamin=null;
            txtTanggal.setText("");
            txtAlamat.setText("");
            cbJurusan.setSelectedIndex(-0);
            cbFakultas.setSelectedIndex(-0);
            cbAngkatan.setSelectedIndex(-0);
            txtNim.requestFocus();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan");
            
         }
            Statatement.Close();
        } catch (Exception exc) {
            System.err.println("Terjadi Kesalahan :" + exc);
     }
}

    }//GEN-LAST:event_bnSimpanActionPerformed

    private void bnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnRefreshActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bnRefreshActionPerformed

    private void bnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnUbahActionPerformed
    
    }//GEN-LAST:event_bnUbahActionPerformed

    private void bnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnHapusActionPerformed
        // TODO add your handling code here:
        String sql = "DELETE FROM biodata_mhs WHERE nim=?";
    try {
        java.sql.Statement statement = konekasi.getConnection.creatStatement();
         statement.executeUpdate(sql);
         JOptionPane.showMessageDialog(this, "Terjadi error pada saat delete data");
         statement.close();
         txtNim.setText("");
         txtNama.setText("");
        String jeniskelamin = null;
        if (rbLaki.isSelected()) {
            jeniskelamin = "L";
        }
        else if (rbPerempuan.isSelected()) {
    jeniskelamin = "P";
}
        txtTanggal.getText();
        txtAlamat.getText();
        cbJurusan.getSelectedItem();
        cbFakultas.getSelectedItem();
        cbAngkatan.getSelectedItem();
         txtNim.requestFocus();
         TampilData();
      } catch (SQLException exc) {
          System.err.println(sql);
          System.err.println("Error : " + exc);

    }//GEN-LAST:event_bnHapusActionPerformed

    private void bnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnBatalActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       int baris = biodata_mhs.getSelectedRow();
       if (baris != -1) {
           txtNim.setText(biodata_mhs.getValueAt(baris, 0).toString());
           txtNama.setText(biodata_mhs.getValueAt(baris, 1).toString());
           if ("L".equals(biodata_mhs.getValueAt(baris, 2).toString())) {
               rbLaki.setSelected(true);
           } else {
               rbPerempuan.setSelected(true);
        }
    }
       txtTanggal.setText(biodata_mhs.getValueAt(baris, 0).toString());
       txtAlamat.setText(biodata_mhs.getValueAt(baris, 3).toString());
       cbJurusan.setSelectedItem(biodata_mhs.getValueAt(baris, 3).toString());
       cbFakultas.setSelectedItem(biodata_mhs.getValueAt(baris, 3).toString());
       cbAngkatan.setSelectedItem(biodata_mhs.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(biodata_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(biodata_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(biodata_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(biodata_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new biodata_mhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnBatal;
    private javax.swing.JButton bnHapus;
    private javax.swing.JButton bnRefresh;
    private javax.swing.JButton bnSimpan;
    private javax.swing.JButton bnUbah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAngkatan;
    private javax.swing.JComboBox<String> cbFakultas;
    private javax.swing.JComboBox<String> cbJurusan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLable1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables

    private void Koneksi() {
        throw new UnsupportedOperationException(""); //To change body of generated methods, choose Tools | Templates.
    }

    private void Tampilan() {//membuat tampilan model tabel
DefaultTableModel model = new DefaultTableModel();
model.addColumn("NIM");
model.addColumn("Nama Mahasiswa");
model.addColumn("Jenis Kelamin");
model.addColumn("Tanggal Lahir");
model.addColumn("Alamat");
model.addColumn("Jurusan");
model.addColumn("Fakultas");
model.addColumn("Angkatan");
biodata_mhs.setModel(model);

//menampilkan data database kedalam tabel
try {
    java.sql.Statement statement = konekasi.getConnection.creatStatement();
    ResultSet data = Statatement.executeUpdate("SELECT * FROM biodata_mhs;");
    while (data.next()) {
         model.addRow(new Object[]{
            data.getString("nim"),
            data.getString("nama"),
            data.getString("jenis_kelamin"),
            data.getString("jurusan"),
            data.getString("semester")
         });
         biodata_mhs.setModel(model);
    }
} catch (Exception e) {
    System.err.println("Terjadi Kesalahan :" + e);
}
    }
}